spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.249.223:8848
    gateway:
      routes:
        - id: route1 #路由名称
          uri: http://www.baidu.com  #路由地址
          predicates: #断言 即规则判断
            - Query=url,baidu  #参数url=baidu
        - id: route2
          uri: http://www.jd.com
          predicates:
            - Query=url,jd